server:
  port: 18085
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
spring:
  thymeleaf:
    cache: false
  application:
    name: item
  main:
    allow-bean-definition-overriding: true
# 生成静态页的位置
pagepath: C:\Users\Administrator\IdeaProjects\lego\lego-parent\lego-web\lego-web-item\src\main\resources\static